### PR TITLE
updated ui

### PR DESCRIPTION
**Pull request by dyarawilliams**
Issue #44

### CODE REVIEW

**Comment by dyarawilliams** [comment]
Everything below Line 213 is commented out

**Comment by flyingsonu122** [comment]
- host your [new-interface](https://github.com/dyarawilliams/tarana/tree/new-interface) branch and share link here
- fetch all images and songs from play.js files
- make it fully working
- also make it mobile responsive

**Comment by dyarawilliams** [comment]
Alright will do :)

**Comment by dyarawilliams** [comment]
My progress thus far .. could use a little more responsiveness but here's what I have. 

https://tranquil-creponne-4e590d.netlify.app/

**Comment by flyingsonu122** [comment]
Thanks @dyarawilliams  for your valuable contributions, merging this.

If want to improve further, make changes and create new PR.

**Comment by dyarawilliams** [comment]
@flyingsonu122 Okay thank you for allowing me to be a part of your project. :)

**Pull request merged**
