### PR TITLE
#25 Fixed - Added Bottom Up top button

### LINKED ISSUE #25: Feature : Addition of scroll back to top button
### Description

- I want to add scroll back to top button for this website. 
- This will improve website’s **User Experience(UX)** with an arrow, when a user start scrolling the page. The page smoothly scrolls back to top when the the button is clicked.

### Screenshot

- Please assign me to work for this feature under GSSOC '22.

Image

### PR DESCRIPTION
**Pull request by TG922**
## 🛠️ Fixes Issue

Closes #25

## 👨‍💻 Changes Done

- Added bottom up top button for the **Music Player Website** according to the theme.
- This will improve the website’s User Experience(UX) with an arrow when a user starts scrolling the page. The page smoothly scrolls back to the top when the button is clicked.

## 📷 Screenshots

Image50

### CODE REVIEW

**Review by flyingsonu122 — CHANGES_REQUESTED** [review]
make it into **develop** branch

**Comment by TG922** [comment]
> make it into **develop** branch

OK Will do ASAP today

**Comment by TG922** [comment]
@flyingsonu122 I'm having issue when pushing it to develop branch can it add it to main??

**Comment by flyingsonu122** [comment]
> @flyingsonu122 I'm having issue when pushing it to develop branch can it add it to main??

fetch **upstream** changes of **every** branch and then add your changes, then create PR to **develop** branch

**Pull request closed without merging**
