### PR TITLE
fetched recently played songs and recommendations

### PR DESCRIPTION
**Pull request by Abhijeet-2003**
Solved #129. Successfully fetched Recently Played Songs and Recommendations using Spotify API. The search bar is also functional for all top songs, recently played songs, and recommendations.

### CODE REVIEW

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 8 11 21 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 8 11 50 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 8 11 37 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-26 at 8 11 32 PM

**Review by flyingsonu122 — APPROVED** [review]
Looks good to me

Thanks for your valuable contributions

**Pull request merged**
