### PR TITLE
Solved #97. Fetched songs, user information, user devices using Spotify API. 

### PR DESCRIPTION
**Pull request by Abhijeet-2003**
I have successfully fetched the _User's Top Tracks, User Devices and User Information_ using the **Spotify API**. The **_Search Bar_** is also functional and you can search for any of your top tracks. I've also created an **appropriate UI** for all the fetched data.
Playing the songs is not possible as it requires the user to have **Spotify PREMIUM**.

There are a few things to keep in mind for anyone who is going to work further on this project.

1. Firstly, you need to get a **Client ID** and a **Client Secret**. For that, you'll have to go to [https://developer.spotify.com/](url), log in and go to the dashboard, then click on 'Create an App' and fill in the necessary details.
2. You'll see a page with your **Client ID** and a **Client Secret**. On the same page, you need to click on "_Users and Access_" and enter the required details. After doing this, click on "_Edit Settings_" and add a **Redirect URI** which should be the **_same_** as the URI of "_index.html_ (not the one inside **user folder**)". In my case, it was "http://127.0.0.1:5500/index.html". Similarly, in "_spotifyApi.js- Line 4_" and in "_auth.js- Line 1_" modify the **var redirect_uri**.
3. After doing all this, you can now run "_auth.html_". Fill in the required details. If it shows "_Invalid Redirect URI_", please verify whether the **Redirect URI** you entered previously are correct and matching with each other. If everything is right, you'll see a Spotify Authorization page.
4. After you click on "Agree", you'll be redirected to "_index.html_". Refresh the page once or maybe twice and you'll get your top tracks, user information, etc. If there's any error, try to refresh the Spotify developer page and index.html too.

### CODE REVIEW

**Comment by flyingsonu122** [comment]
@Abhijeet-2003 how have you checked code is running or not

If running please share screenshots

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-23 at 7 30 50 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-23 at 7 33 28 PM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-23 at 7 33 55 PM

**Comment by Abhijeet-2003** [comment]
@flyingsonu122 . Please have a look.

**Review by flyingsonu122 — APPROVED** [review]
Looks good to me

@Abhijeet-2003 thanks for your valuable contributions

**Comment by Abhijeet-2003** [comment]
@flyingsonu122 . I haven't received any points for this pr.

**Comment by flyingsonu122** [comment]
You will get it , no need to worry

**Pull request merged**
