### PR TITLE
Added LEARN.md

### PR DESCRIPTION
**Pull request by Abhijeet-2003**
Solved #83.

### CODE REVIEW

**Review by flyingsonu122 — APPROVED** [review]
Looks good to me

Thanks

**Comment by Abhijeet-2003** [comment]
@flyingsonu122. It was labelled as 20 points.

**Comment by flyingsonu122** [comment]
Done

**Comment by Abhijeet-2003** [comment]
Please award points for my 3 merged PRs and 2 issues raised. It's been a long time. 😅 @flyingsonu122

**Comment by flyingsonu122** [comment]
Can you share me your total points till now for this program codepeak22

**Comment by Abhijeet-2003** [comment]
Yeah, for all the 3 PRs - 60 points.
and for the 2 issues I've raised #130 , #129 - depending on their difficulty, you can decide how uch points to award for raising them.

**Comment by flyingsonu122** [comment]
I thought it will be given by adding just levels


But if not happening then will give it manually on  discord server

**Comment by Abhijeet-2003** [comment]
Yeah sure. I think most of the other mentors are awarding points on discord manually.

**Comment by letsintegreat** [comment]
@Abhijeet-2003 @flyingsonu122 This PR has been allotted points, I will check for #128 and #131 and make sure they are allotted too. Sorry, the bot was down for some time.

**Comment by flyingsonu122** [comment]
> @Abhijeet-2003 @flyingsonu122 This PR has been allotted points, I will check for #128 and #131 and make sure they are allotted too. Sorry, the bot was down for some time.

@Abhijeet-2003 @letsintegreat Kindly update if points are allotted, else confirm me I will give it manually on discord

**Comment by flyingsonu122** [comment]
Kindly tag me for every message

**Comment by Abhijeet-2003** [comment]
> > @Abhijeet-2003 @flyingsonu122 This PR has been allotted points, I will check for #128 and #131 and make sure they are allotted too. Sorry, the bot was down for some time.
> 
> @Abhijeet-2003 @letsintegreat Kindly update if points are allotted, else confirm me I will give it manually on discord

Points are alloted. @flyingsonu122

**Comment by flyingsonu122** [comment]
> > > @Abhijeet-2003 @flyingsonu122 This PR has been allotted points, I will check for #128 and #131 and make sure they are allotted too. Sorry, the bot was down for some time.
> > 
> > 
> > @Abhijeet-2003 @letsintegreat Kindly update if points are allotted, else confirm me I will give it manually on discord
> 
> Points are alloted. @flyingsonu122

thanks for the update

**Pull request merged**
