### PR TITLE
fixes #41 Responsive-chenges on  develop branch

### LINKED ISSUE #41: Make it responsive
Make website response to every screen sizes

### PR DESCRIPTION
**Pull request by mayank-del**
@flyingsonu122 , I made the the same changes for develop branch as well .Now, you can merge it

### CODE REVIEW

**Comment by flyingsonu122** [comment]
PR Should be in **develop** branch

**Comment by mayank-del** [comment]
> PR Should be in **develop** branch

Yes, @flyingsonu122  sir, you can see on the top , i made pr from develop branch

**Comment by flyingsonu122** [comment]
> > PR Should be in **develop** branch
> 
> Yes, @flyingsonu122 sir, you can see on the top , i made pr from develop branch

make pr to not from 
image

**Comment by mayank-del** [comment]
> > > PR Should be in **develop** branch
> > 
> > 
> > Yes, @flyingsonu122 sir, you can see on the top , i made pr from develop branch
> 
> make pr to not from image

@flyingsonu122 sir, I have made the changes to developer branch.

**Review by flyingsonu122 — APPROVED** [review]
next time make some **valuable** contributions

**Pull request merged**
