### PR TITLE
Changes Lot Of CSS to Make it Much Responsive

### LINKED ISSUE #75: Resolve The Breaking Code
@flyingsonu122  Assign Please, I will Resolve it

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
THE CHANGES THAT I HAVE MADE:

CLOSES #75
 
1. I HAVE CHANGED ALOT OF CSS CODE TO MAKE IT MUCH BETTER IN FORM OF CODE. 
2. REMOVED POSITION PROPERTIES FROM EVERYWHERE WHICH CAUSE BUGS IN THE CODE.
3. A DIFFERENT HEADER  SECTION IS INTRODUCED.
4. HERARCHY OF DIVS IS SETTLE NOW.
{FOR EXAMPLE : FIRST NAV-> THEN MAIN->FOOTER} EARLIER IT WAS NOT LIKE THIS
5.  FONT STYLING CHANGED

CONCLUSION

THIS IS BETTER FOR TESTING AND SETTING UP NEW THINGS IN THE PROJEC. BECASUE EARLIER WHEN I WAS ADDING A BUTTON OR ANYTHING, IT WAS BREAKING THE WHOLE CODE. NOW NOTHING WILL HAPPEN LIKE BEFORE.

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@flyingsonu122  Have made a lot may changes . I changes all the css because the css was the only thing that was breaking everything up.

**Comment by flyingsonu122** [comment]
Add screenshot

**Comment by Abh1shekSingh** [comment]
> Add screenshot

t1
t2
t3
t4

**Comment by flyingsonu122** [comment]
improve sound bar

**Comment by flyingsonu122** [comment]
host your https://github.com/Abh1shekSingh/tarana/tree/resolve  resolve branch so that i can see live demo


after hosting share me link

**Comment by Abh1shekSingh** [comment]
I am saying, this interface is only so that, i could work with backend
easily. Later I will make it much better.

**Comment by flyingsonu122** [comment]
@Abh1shekSingh you create pr in **auth** branch only

**Comment by Abh1shekSingh** [comment]
> @Abh1shekSingh you create pr in **auth** branch only

You didn't add the label for this PR. the marks

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Kindly Add the Label and marks for this PR

**Comment by Abh1shekSingh** [comment]
I changes the whole CSS buddy. and Level 1 ?

**Pull request merged**
