### PR TITLE
Songs added to music folder and json

### PR DESCRIPTION
**Pull request by UdAyAn123**
I added 6 songs of anuv jain and ashu shukla

### CODE REVIEW

**Comment by flyingsonu122** [comment]
@UdAyAn123 read all instructions, understand codebase and then create PR.

**Comment by UdAyAn123** [comment]
Respected Sir I am starting with open source so can you please tell me more about this repository
Regards, hoping to learn from you 
Thank You

**Comment by flyingsonu122** [comment]
> Respected Sir I am starting with open source so can you please tell me more about this repository Regards, hoping to learn from you Thank You

@

> Respected Sir I am starting with open source so can you please tell me more about this repository Regards, hoping to learn from you Thank You

@eshan1925 please help here

**Comment by flyingsonu122** [comment]
> Respected Sir I am starting with open source so can you please tell me more about this repository Regards, hoping to learn from you Thank You

@eshan1925 please help here

**Comment by eshan1925** [comment]
> Respected Sir I am starting with open source so can you please tell me more about this repository Regards, hoping to learn from you Thank You

Hey, @UdAyAn123 So basically open source is all about coding and contribution.


If you don't know the basics of GitHub itself watch this video: [link](https://www.youtube.com/watch?v=apGV9Kg7ics)

Now if you want to get started with the project we will be definitely trying to build a website just like Spotify but with new Ui's and some extra features. So we will be mainly needing the dynamic fetching of songs from some source. So please work on that and come up with new ideas.

For now, we are finalizing the design of the website and you can find its reference issue in issue #20 .

Once the design gets finalized we will proceed further.
image

**Pull request closed without merging**
