### PR TITLE
routesAdded

### PR DESCRIPTION
**Pull request by ayush25102001**
* Created the userModel.
* Set up backend routes for login and signUp.
* Connected to the database locally in which the entries are pushed.

- SIGN UP:
*SUCCESSFULL:

*UNSUCESSFULL(same email used again):

-LOGIN:
*SUCCESSFULL:

*UNSUCESSFULL(Incorrect password):

-DATABASE ENTRY:

(Password hashed)

Please review @flyingsonu122

### CODE REVIEW

**Comment by ayush25102001** [comment]
> make it on **develop** branch

done !!

**Comment by ayush25102001** [comment]
Please review @flyingsonu122

**Comment by flyingsonu122** [comment]
@eshan1925 please review this

**Comment by eshan1925** [comment]
Hey @ayush25102001 what is this issue regarding to?

**Comment by ayush25102001** [comment]
> Hey @ayush25102001 what is this issue regarding to?

Sir, there is a pinned issue for adding login and signUp components that includes various more tasks.
Here, I just created the login and signUp endpoints at the backend.
Currently I am making requests through postman and storing the credentials inside the database locally.

**Comment by eshan1925** [comment]
ok

**Comment by ayush25102001** [comment]
Can u merge the PR @eshan1925 @flyingsonu122

**Comment by ayush25102001** [comment]
> Can u merge the PR @eshan1925 @flyingsonu122

Sir @flyingsonu122 labels ??

**Review by flyingsonu122 — COMMENTED** [review]
Thank you for your valuable contributions

**Comment by ayush25102001** [comment]
> Thank you for your valuable contributions

Sir the PR points are not getting reflected in the leaderboard

**Comment by ayush25102001** [comment]
> > Thank you for your valuable contributions
> 
> Sir the PR points are not getting reflected in the leaderboard

@flyingsonu122

**Pull request merged**
