### PR TITLE
#15 Code Optimization

### LINKED ISSUE #15: Code Optimization and File Ordering
In the Project I found all CSS files and JS files clubbed together.

So they can be organised in directory to increase readability of reduce complexity.

Also it found two JS function code getting repeated, so we can organise them in single JS file and just call them instead of writing those code again.

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
Closes #15

I have re-optimized the code

### CODE REVIEW

**Review by flyingsonu122 — CHANGES_REQUESTED** [review]
Make it into **develop** branch

**Comment by Kumar-laxmi** [comment]
> Make it into **develop** branch

@flyingsonu122 done

**Comment by Kumar-laxmi** [comment]
@flyingsonu122 Please assign the label as ```GSSoC22``` & ```Level2``` so that this PR is counted in LeaderBoard

**Review by flyingsonu122 — CHANGES_REQUESTED** [review]
have you **checked** whether it's working or not?

**Comment by Kumar-laxmi** [comment]
@flyingsonu122 It is working

**Review by flyingsonu122 — APPROVED** [review]

**Pull request merged**
