### PR TITLE
Created user profile with albums, artists, playlists, liked tracks

### PR DESCRIPTION
**Pull request by Abhijeet-2003**
Solved #130. On clicking the icon with username, the user profile will open up displaying the saved albums, followed artists, saved playlists and liked songs.

### CODE REVIEW

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-31 at 2 39 41 AM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-31 at 2 39 57 AM

**Comment by Abhijeet-2003** [comment]
Screenshot 2022-12-31 at 2 40 13 AM

**Comment by Abhijeet-2003** [comment]
@flyingsonu122. Any updates regarding this pr?

**Review by flyingsonu122 — APPROVED** [review]
Thanks for your valuable contributions

**Comment by Abhijeet-2003** [comment]
@flyingsonu122 . I have not received points for creating issues #129 #130. And also for this PR #134. Kindle check.

**Comment by flyingsonu122** [comment]
It takes time for the bot to work.

Please check after some time.

**Pull request merged**
