### PR TITLE
UI created with full responsiveness 

### PR DESCRIPTION
**Pull request by Tushar98644**
https://user-images.githubusercontent.com/107763774/208285479-4929b8dd-34ab-44a2-a244-833f71ef5eec.mp4

### CODE REVIEW

**Comment by flyingsonu122** [comment]
Kindly work on open issues only,

**Comment by Tushar98644** [comment]
> Kindly work on open issues only,

this issue is open and is assigned to me ...kindly check @flyingsonu122

**Comment by flyingsonu122** [comment]
This design is not suitable, hence closed


Please discuss design first on issues comments before working and creating pull request

**Comment by Tushar98644** [comment]
> This design is not suitable, hence closed
> 
> Please discuss design first on issues comments before working and creating pull request

ok...

**Pull request closed without merging**
