### PR TITLE
Added FB AUTH

### LINKED ISSUE #72: [FEATURE] I WILL ADD FACEBOOK AUTH
### Description

FACEBOOK AUTHENCTICATION IN TARANA

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
@flyingsonu122  Please Review I have added Facebook Authentication successfully
closes #72

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Please review my PR

**Comment by flyingsonu122** [comment]
Show profile photo or some details after login in

**Comment by Abh1shekSingh** [comment]
> Show profile photo or some details after login in on main page

will do in new PR. I was also having the same idea.

**Comment by Abh1shekSingh** [comment]
> Show profile photo or some details after login in on main page

will do in new PR. I was also having the same idea.

**Comment by Abh1shekSingh** [comment]
Bhai Yrr, sath mein internship bhi chl rhi hai, isiliye bol raha tha time
nhi de paa raha Mein.

**Comment by flyingsonu122** [comment]
take your time

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Added user Name on the top after he logs in 
sample

**Comment by Abh1shekSingh** [comment]
@flyingsonu122 Please review now

**Pull request merged**
